### ISSUE TITLE
Swagger UI 

### ISSUE THREAD

**Issue by fayaz07** [stackinflow/node-rest-api-starter#10]

**Comment by shubhamofbce** [comment]
Are you working on this @fayaz07 ??

**Comment by fayaz07** [comment]
No, I didn't start working on it yet

**Comment by shubhamofbce** [comment]
Do you just want swagger UI integration or something else?? You can specify details , I would like to work on this

**Comment by fayaz07** [comment]
@shubhamofbce, thank you for your interest

I guess adding swagger as dependency will be inefficient, (not my personal view, I read this somewhere on the internet)
So, maybe it's good to have just `yaml`

**Comment by shubhamofbce** [comment]
Ok I will also do some research on this and then we will discuss what we can do @fayaz07

**Comment by fayaz07** [comment]
yeah sure @shubhamofbce

**Comment by fayaz07** [comment]
Hi @shubhamofbce please join our gitter channel for further discussions
https://gitter.im/stackinflow/Nodejs
