### ISSUE TITLE
dev and prod environment easy shifting 

### ISSUE THREAD

**Issue by fayaz07** [stackinflow/node-rest-api-starter#4]

**Comment by fayaz07** [comment]
@prudhvir3ddy what should we actually do here

**Comment by prudhvir3ddy** [comment]
Different database configuration, url configuration can go in here.

**Comment by fayaz07** [comment]
when you change the value in `.env` file the environment automatically changes
if the user specifically wants to do it programmatically, then they can add this snippet
```
process.env.NODE_ENV = "dev"
```

**Comment by fayaz07** [comment]
@prudhvir3ddy closing this issue, as we don't need to take any actions on this
